### ISSUE TITLE
alglib318hpc_net2

### ISSUE THREAD

**Issue by mfhw20** [user29A/JPFITS#2]
Hello,

where do you get "alglib318hpc_net2".

Google does not have a single hit.

Thanks

**Comment by user29A** [comment]
Just download the release package with the dll's you need:

https://github.com/user29A/JPFITS/releases/tag/2021.12.13

(zip file: https://github.com/user29A/JPFITS/releases/download/2021.12.13/JPFITS.zip )

Cheers,

Joe

**Comment by mfhw20** [comment]
Thank you

Franz

Am Mo., 13. Dez. 2021 um 17:28 Uhr schrieb user29A ***@***.***
