### ISSUE TITLE
JPChart

### ISSUE THREAD

**Issue by SteveRowl** [user29A/JPFITS#3]
Hi. I have downloaded JPFITS and also alglib318gpl_net5 and referenced this. I still have a few error in that the compiler cannot find "JPChart". 
Can you advise please?
Steve

**Comment by user29A** [comment]
Hi Steve,

JPChart should be one of the dll in the release ZIP:

https://github.com/user29A/JPFITS/releases/download/2021.12.16/JPFITS.zip

Just make sure that all of the dll's in the ZIP file are "beside" the JPFITS.dll in the directory where you use it.

If you still encounter a problem please let me know.

Cheers,

Joe

**Comment by SteveRowl** [comment]
Many thanks Joe.

I am puzzled why I cannot see the .zip file in the GIT repository - I am new to GIT. Of course I have the files now thanks to the link you sent.

How was the JPChart.dll created. Is it in PHP from https://jpgraph.net?

**Comment by user29A** [comment]
Hi Steve,

JPChart is just a Visual Studio .net Chart control with some custom functionality:

https://github.com/user29A/JPChart

It is used when plotting FITS Bintable data in one of the JPFITS controls, etc.

Cheers,

Joe
